name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: SPM build
      run: swift build

    - name: Lint Podspec
      run: |
        set -eo pipefail
        pod lib lint --allow-warnings --use-libraries
    
    - name: Carthage build
      run: ./scripts/carthage.sh build --platform "ios,macos" --no-skip-current
      
    - name: Carthage XCFramework build
      run: |
        brew update carthage
        carthage build --platform "ios,macos" --no-skip-current --use-xcframeworks
